### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by betzerra** [Canillitapp/headlines-iOS#48]
- [x] Error on reactions service - `request_failed` (*)
- [x] Error on news service - `request_failed` (*)
- [x] Reactions by tapping the reaction button. - `add_reaction_collection_cell_pressed`
- [x] Reactions by long pressing the cell. - `add_reaction_long_press`
- [x] User taps reaction emoji buttons. - `emoji_reaction_pressed`
- [x] User taps add reaction button. - `add_reaction_button_pressed`
- [x] User is at "Destacados". - `trending_appear`
- [x] User is at "Popular". - `popular_appear`
- [x] User is at "Reciente". - `recent_appear`
- [x] User is at "Reacciones". - `my_reactions_appear`
- [x] User is at "Search". - `search_appear`
- [x] User is at reactions picker. - `reactions_picker_appear`
- [x] User taps a trending card. - `trending_item_tapped`
- [x] User taps a news cell. - `news_item_tapped`

(*) includes "iCloud account is needed"
