### ISSUE TITLE
Emoji reactions on news

### ISSUE THREAD

**Issue by betzerra** [Canillitapp/headlines-iOS#6]
- [x] Show user's emoji reactions #11 
- [x] Emoji fast picker #12 
- [x] Emoji extended picker #13 

Implementing emoji reactions _a la Slack_. Any thoughts?

<img src="https://cloud.githubusercontent.com/assets/681600/24984215/76f9f862-1fc2-11e7-833c-ad0908665812.png" width="200" /> <img src="https://cloud.githubusercontent.com/assets/681600/24984220/7f551992-1fc2-11e7-8e1d-68da37330131.png" width="200" /> <img src="https://cloud.githubusercontent.com/assets/681600/24984221/80b99510-1fc2-11e7-8bde-153bc92bd893.png" width="200" />

**Comment by betzerra** [comment]
![new_mockups](https://www.dropbox.com/s/sutdmdc17s17xrc/Screenshot%202017-04-21%2023.10.46.png?dl=1)
